try {

    console.log (c);
    let c = 3
  
  } catch (err) {
  
    console.log('let must be declared')
  
  }